print('Agamvir Singh Brar\n Hello, I am execited to learn Python')
print('Let\'s Play')
print("I like Fortnite\t I like food\t I like gaming\t I like TV\t I like anime")
print("canada\nindia\nu.a.e\n usa\nspain")
print("shai paneer\tnaan\tburger\tpizza\tkulfi")
print("it is easier to write in python, it gives advantage if know how to use it, it is fun")
print("Twinkle, twinkle, little star,\n\t\tHow I wonder what you are,\n\t\t\tUp above the world so high,\n\t\t\t\tLike a diamond in the sky.")
