print(" coding is writing to make games and programs")
print(" python is a program that is used te teach people how to code")
print("omelete\ngrilled cheese sandwich and milkshake\ngoat")
print(" Hurray! I am Loving Python.")
print("covid is bad\ncovid kill people\ncovid was born from china\ncovid spread all around the world\ncovid has vaccine")
print("blue\nsilver\ngold\nyellow\nred")
print("tobico, falls, dubai, mukhsar, montreal")
print("it is boring\t to much effort, wasted time")
print("when the blazing sun is gone,\n\t\tWhen he nothing shines upon,\n\tThen you show your little light\n,\t\tTwinkle, twinkle, all the night,\n\nwhen the blazing sun is gone,\t\t\n\t\tWhen he nothing shines upon")
print("black = symbols and names most code text is colored black\npurple = built-in commands python command, such as print are shown in purple,\nblue = output any text produced when a progam runs in blue,\nsred = errors python uses red to alert you to any errors in your code,\norange = keywords certain words such as if and else, are special words that python uses. they are called keywords and shown in orange,\ngreen =  text in qoutes marks is green. A green bracket around text shows you're missing a qoute mark.")
