print("it di not descibe a")
print("error is that when b is bescibwed it is descibwed after the pwint line")
print(" errorar is the print is capitalazieded")
print("errorar is it did not close the qoutes")
print("errorar is the braket was not close")
print("errorar is that it is mutilplying a srting")
print("erroara isn that oink-achu you caan nooot comapre srtring with intedtgrer")
print("erroarsz charizard the errorar that the appleee speeelingn is tort")
