secret_word = 'pronounciation'
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
letter = input("Enter a letter: ")
print('Your answer is',letter in secret_word)
final_guess = input("Enter your final guess ")
print('Your guess is',final_guess in secret_word)

##name = input("Enter your name please ")
##grade = input("Enter your grade please ")
##science = float(input("Enter your science mark in percentage"))
##math = float(input("Enter your math mark in percentage"))
##language = float(input("Enter your language mark in percentage"))
##gym = float(input("Enter your gym mark in percentage"))
##social_studies = float(input("Enter your social studies mark "))
##Average_mark = (science+math+language+gym+social_studies)
##Final_mark = (Average_mark/5)
print('Your final mark is',Final_mark)
if Final_mark > 25 and Final_mark < 50:
    print('You got c')
if Final_mark > 20  and Final_mark < 25:
    print('You got d')
if Final_mark > 50  and Final_mark < 75:
    print('You got b')
if Final_mark > 75  and Final_mark < 100:
    print('You got a')
